/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnimalCategory = { 'cat' : null } |
  { 'cow' : null } |
  { 'dog' : null } |
  { 'other' : null } |
  { 'bird' : null } |
  { 'fish' : null } |
  { 'goat' : null } |
  { 'sheep' : null } |
  { 'reptile' : null } |
  { 'buffalo' : null } |
  { 'smallAnimal' : null };
export interface Listing {
  'id' : ListingId,
  'status' : ListingStatus,
  'title' : string,
  'photoUrls' : Array<string>,
  'owner' : Principal,
  'description' : string,
  'isActive' : boolean,
  'timestamp' : Time,
  'category' : AnimalCategory,
  'isVip' : boolean,
  'price' : bigint,
  'location' : string,
}
export type ListingId = bigint;
export type ListingStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Message {
  'listingId' : [] | [ListingId],
  'text' : string,
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
}
export interface PublicUserProfile {
  'bio' : string,
  'displayName' : string,
  'registrationTimestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'lastLoginTime' : bigint,
  'contactInfo' : [] | [string],
  'displayName' : string,
  'mobileNumber' : [] | [string],
  'registrationTimestamp' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveListing' : ActorMethod<[ListingId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, bigint, AnimalCategory, string, Array<string>, boolean],
    ListingId
  >,
  'deleteListing' : ActorMethod<[ListingId], undefined>,
  'deleteListingAdmin' : ActorMethod<[ListingId], boolean>,
  'getAllListings' : ActorMethod<[], Array<Listing>>,
  'getAllListingsAdmin' : ActorMethod<[], Array<Listing>>,
  'getAllMobileNumbers' : ActorMethod<[], Array<[Principal, string]>>,
  'getAllUsersWithActivity' : ActorMethod<
    [],
    Array<[Principal, string, bigint]>
  >,
  'getApprovedListingsCount' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[Principal], Array<Message>>,
  'getListings' : ActorMethod<[], Array<Listing>>,
  'getMobileNumber' : ActorMethod<[], [] | [string]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPendingListings' : ActorMethod<[], Array<Listing>>,
  'getPendingListingsCount' : ActorMethod<[], bigint>,
  'getProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'getTotalListingsCount' : ActorMethod<[], bigint>,
  'getTotalLoginsCount' : ActorMethod<[], bigint>,
  'getTotalUsersCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listConversations' : ActorMethod<[], Array<Principal>>,
  'rejectListing' : ActorMethod<[ListingId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    undefined
  >,
  'sendMessage' : ActorMethod<[Principal, [] | [ListingId], string], undefined>,
  'signUp' : ActorMethod<[string, string], string>,
  'updateListing' : ActorMethod<
    [
      ListingId,
      string,
      string,
      bigint,
      AnimalCategory,
      string,
      Array<string>,
      boolean,
      boolean,
    ],
    undefined
  >,
  'upsertProfile' : ActorMethod<[string, string, [] | [string]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];