/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AnimalCategory = IDL.Variant({
  'cat' : IDL.Null,
  'cow' : IDL.Null,
  'dog' : IDL.Null,
  'other' : IDL.Null,
  'bird' : IDL.Null,
  'fish' : IDL.Null,
  'goat' : IDL.Null,
  'sheep' : IDL.Null,
  'reptile' : IDL.Null,
  'buffalo' : IDL.Null,
  'smallAnimal' : IDL.Null,
});
export const ListingId = IDL.Nat;
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'contactInfo' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'mobileNumber' : IDL.Opt(IDL.Text),
  'registrationTimestamp' : Time,
});
export const Message = IDL.Record({
  'listingId' : IDL.Opt(ListingId),
  'text' : IDL.Text,
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const Listing = IDL.Record({
  'id' : ListingId,
  'title' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'timestamp' : Time,
  'category' : AnimalCategory,
  'isVip' : IDL.Bool,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        AnimalCategory,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [ListingId],
      [],
    ),
  'deleteListing' : IDL.Func([ListingId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
  'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'getMobileNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Opt(ListingId), IDL.Text],
      [],
      [],
    ),
  'signUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateListing' : IDL.Func(
      [
        ListingId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        AnimalCategory,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'upsertProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AnimalCategory = IDL.Variant({
    'cat' : IDL.Null,
    'cow' : IDL.Null,
    'dog' : IDL.Null,
    'other' : IDL.Null,
    'bird' : IDL.Null,
    'fish' : IDL.Null,
    'goat' : IDL.Null,
    'sheep' : IDL.Null,
    'reptile' : IDL.Null,
    'buffalo' : IDL.Null,
    'smallAnimal' : IDL.Null,
  });
  const ListingId = IDL.Nat;
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'contactInfo' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'mobileNumber' : IDL.Opt(IDL.Text),
    'registrationTimestamp' : Time,
  });
  const Message = IDL.Record({
    'listingId' : IDL.Opt(ListingId),
    'text' : IDL.Text,
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const Listing = IDL.Record({
    'id' : ListingId,
    'title' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'timestamp' : Time,
    'category' : AnimalCategory,
    'isVip' : IDL.Bool,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          AnimalCategory,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [ListingId],
        [],
      ),
    'deleteListing' : IDL.Func([ListingId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getListing' : IDL.Func([ListingId], [IDL.Opt(Listing)], ['query']),
    'getListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'getMobileNumber' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Opt(ListingId), IDL.Text],
        [],
        [],
      ),
    'signUp' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateListing' : IDL.Func(
        [
          ListingId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          AnimalCategory,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'upsertProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };